#!/usr/bin/python3

import json
from models.base_model import BaseModel


class FileStorage:
    __file_path = 'file.json'
    __objects = {}

    def all(self):
        return self.__objects

    def new(self, obj):
        self.__objects[f'{obj.__class__.__name__}.{obj.id}'] = obj

    def save(self):
        with open(self.__file_path, 'w') as f:
            obj_dict = {}
            for k, v in self.__objects.items():
                obj_dict[k] = v.to_dict()
            json.dump(obj_dict, f)

    def reload(self):
        try:
            with open(self.__file_path, 'r') as f:
                obj_dict = json.load(f)
                for k, v in obj_dict.items():
                    class_name, obj_id = k.split('.')
                    obj_dict['__class__'] = class_name
                    cls_obj = eval(class_name)
                    init_cls_obj = cls_obj(**obj_dict)
                    #obj = eval(class_name)(**obj_dict)
                    self.__objects[k] = init_cls_obj
        except Exception:
            pass
