#!/usr/bin/env bash
# while and case

count=1
while [ $count -le 20 ]; do
	echo "$count"
	case $count in
		4)
			echo "bad luck from China"
			;;
		8)
			echo "bad luck from Japan"
			;;
		17 ) echo "bad luck from Itly" ;;
	esac
	count=$((count+1))
done
